data:
    name: 'coco'
    resize: [240,320]
    image_train_path: ['./data/mg_syn_coco_15e-3/images/train2014',]
    label_train_path: ['./data/mg_syn_coco_15e-3/labels/train2014/',]
    image_test_path: './data/mg_syn_coco_15e-3/images/test2014/'
    label_test_path: './data/mg_syn_coco_15e-3/labels/test2014/'
    augmentation:
        photometric:
            train_enable: true
            test_enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    nb_ellipses: 15
                motion_blur: {max_kernel_size: 3}
        homographic:
            train_enable: true
            test_enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.5707963 #3.1415926
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'superpoint'
    using_bn: false
    grid_size: 8
    pretrained_model: 'none'
    backbone:
        backbone_type: 'VGG'
        vgg:
            channels: [64,64,64,64,128,128,128,128]
            # channels: [64,64,128,128]
    det_head:
        feat_in_dim: 128    # 128
    des_head:
        feat_in_dim: 128    # 128
        feat_out_dim: 256
    det_thresh: 0.001 # 1/65
    nms: 4
    topk: -1
solver:
    grid_size: 8
    loss:
        positive_margin: 1.0
        negative_margin: 0.2
        lambda_d: 0.05
        lambda_loss: 10000
    epoch: 20
    base_lr: 0.001 #0.0001
    train_batch_size: 2
    test_batch_size: 2
    save_dir: './export/superpoint/vgg_backbone'
    # save_dir: './export/superpoint/position_embed'
    model_name: 'superpoint'
    # model_name: 'pe_superpoint'

